DROP TABLE IF EXISTS PROJECT cascade;
DROP TABLE IF EXISTS AUTHOR cascade;

CREATE TABLE PROJECT
(
    PROJECT_ID INT NOT NULL AUTO_INCREMENT,
    PROJECT_NAME VARCHAR(255) NOT NULL,
    CREATION_DATE DATE NOT NULL,
    CONSTRAINT PROJECT_PK PRIMARY KEY (PROJECT_ID)
);

CREATE TABLE AUTHOR
(
    AUTHOR_ID INT NOT NULL AUTO_INCREMENT,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    GRANT_SUM INT NOT NULL,
    PROJECT_ID INT NOT NULL,
    CONSTRAINT AUTHOR_PK PRIMARY KEY (AUTHOR_ID),
    CONSTRAINT AUTHOR_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
    ON DELETE CASCADE ON UPDATE CASCADE
);
